# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-23 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibonacci', '0003_auto_20160823_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibonacciparameters',
            name='exec_time',
            field=models.DecimalField(decimal_places=100, max_digits=1000),
        ),
    ]
