# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-23 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibonacci', '0004_auto_20160823_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibonacciparameters',
            name='exec_time',
            field=models.DecimalField(decimal_places=10, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='fibonacciparameters',
            name='result',
            field=models.CharField(max_length=100000),
        ),
    ]
